language:        node_js
node_js:         12.13.0

# S:             Build Lifecycle
install:
  - npm install
  - export TZ='Asia/Shanghai'

#before_script:
 # - npm install -g gulp

script:
- npm run docs:build

after_script:
  - cd ./docs/.vuepress/dist/
  - git init
  - git config user.name "dongranliu"
  - git config user.email "hysg95324@gmail.com"
  - git add .
  - git commit -m "update post"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E:             Build LifeCycle

branches:
  only:
    - source

env:
 global:
   - GH_REF:     github.com/dongranliu/dongranliu.github.io
